/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProfileRouteImport } from './routes/app/profile'
import { Route as AppPlansRouteImport } from './routes/app/plans'
import { Route as AppDiscoverRouteImport } from './routes/app/discover'
import { Route as AppAdminRouteImport } from './routes/app/admin'
import { Route as AppServersIndexRouteImport } from './routes/app/servers/index'
import { Route as AppServersServerIdRouteImport } from './routes/app/servers/$serverId'
import { Route as AppSSlugRouteImport } from './routes/app/s.$slug'
import { Route as ApiLivekitTokenRouteImport } from './routes/api/livekit/token'
import { Route as AppServersServerIdChannelIdRouteImport } from './routes/app/servers/$serverId.$channelId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlansRoute = AppPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppServersIndexRoute = AppServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => AppRoute,
} as any)
const AppServersServerIdRoute = AppServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => AppRoute,
} as any)
const AppSSlugRoute = AppSSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => AppRoute,
} as any)
const ApiLivekitTokenRoute = ApiLivekitTokenRouteImport.update({
  id: '/api/livekit/token',
  path: '/api/livekit/token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppServersServerIdChannelIdRoute =
  AppServersServerIdChannelIdRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => AppServersServerIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/api/livekit/token': typeof ApiLivekitTokenRoute
  '/app/s/$slug': typeof AppSSlugRoute
  '/app/servers/$serverId': typeof AppServersServerIdRouteWithChildren
  '/app/servers/': typeof AppServersIndexRoute
  '/app/servers/$serverId/$channelId': typeof AppServersServerIdChannelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app': typeof AppIndexRoute
  '/api/livekit/token': typeof ApiLivekitTokenRoute
  '/app/s/$slug': typeof AppSSlugRoute
  '/app/servers/$serverId': typeof AppServersServerIdRouteWithChildren
  '/app/servers': typeof AppServersIndexRoute
  '/app/servers/$serverId/$channelId': typeof AppServersServerIdChannelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/app/admin': typeof AppAdminRoute
  '/app/discover': typeof AppDiscoverRoute
  '/app/plans': typeof AppPlansRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/app/': typeof AppIndexRoute
  '/api/livekit/token': typeof ApiLivekitTokenRoute
  '/app/s/$slug': typeof AppSSlugRoute
  '/app/servers/$serverId': typeof AppServersServerIdRouteWithChildren
  '/app/servers/': typeof AppServersIndexRoute
  '/app/servers/$serverId/$channelId': typeof AppServersServerIdChannelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/discover'
    | '/app/plans'
    | '/app/profile'
    | '/app/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/api/livekit/token'
    | '/app/s/$slug'
    | '/app/servers/$serverId'
    | '/app/servers/'
    | '/app/servers/$serverId/$channelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/admin'
    | '/app/discover'
    | '/app/plans'
    | '/app/profile'
    | '/app/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/app'
    | '/api/livekit/token'
    | '/app/s/$slug'
    | '/app/servers/$serverId'
    | '/app/servers'
    | '/app/servers/$serverId/$channelId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/admin'
    | '/app/discover'
    | '/app/plans'
    | '/app/profile'
    | '/app/settings'
    | '/auth/login'
    | '/auth/signup'
    | '/app/'
    | '/api/livekit/token'
    | '/app/s/$slug'
    | '/app/servers/$serverId'
    | '/app/servers/'
    | '/app/servers/$serverId/$channelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiLivekitTokenRoute: typeof ApiLivekitTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/plans': {
      id: '/app/plans'
      path: '/plans'
      fullPath: '/app/plans'
      preLoaderRoute: typeof AppPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/discover': {
      id: '/app/discover'
      path: '/discover'
      fullPath: '/app/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servers/': {
      id: '/app/servers/'
      path: '/servers'
      fullPath: '/app/servers/'
      preLoaderRoute: typeof AppServersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servers/$serverId': {
      id: '/app/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/app/servers/$serverId'
      preLoaderRoute: typeof AppServersServerIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/s/$slug': {
      id: '/app/s/$slug'
      path: '/s/$slug'
      fullPath: '/app/s/$slug'
      preLoaderRoute: typeof AppSSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/livekit/token': {
      id: '/api/livekit/token'
      path: '/api/livekit/token'
      fullPath: '/api/livekit/token'
      preLoaderRoute: typeof ApiLivekitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/servers/$serverId/$channelId': {
      id: '/app/servers/$serverId/$channelId'
      path: '/$channelId'
      fullPath: '/app/servers/$serverId/$channelId'
      preLoaderRoute: typeof AppServersServerIdChannelIdRouteImport
      parentRoute: typeof AppServersServerIdRoute
    }
  }
}

interface AppServersServerIdRouteChildren {
  AppServersServerIdChannelIdRoute: typeof AppServersServerIdChannelIdRoute
}

const AppServersServerIdRouteChildren: AppServersServerIdRouteChildren = {
  AppServersServerIdChannelIdRoute: AppServersServerIdChannelIdRoute,
}

const AppServersServerIdRouteWithChildren =
  AppServersServerIdRoute._addFileChildren(AppServersServerIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppPlansRoute: typeof AppPlansRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSSlugRoute: typeof AppSSlugRoute
  AppServersServerIdRoute: typeof AppServersServerIdRouteWithChildren
  AppServersIndexRoute: typeof AppServersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppPlansRoute: AppPlansRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
  AppSSlugRoute: AppSSlugRoute,
  AppServersServerIdRoute: AppServersServerIdRouteWithChildren,
  AppServersIndexRoute: AppServersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiLivekitTokenRoute: ApiLivekitTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
